In [146]:
import numpy as np

# Types of Array's

In [147]:
a = np.array([1,2,3])

In [148]:
print(a)
print(type(a))
print(a.dtype)

[1 2 3]
<class 'numpy.ndarray'>
int32


In [149]:
b = np.array([4.0, 5, 9.35])

In [150]:
print(b)
print(type(b))
print(b.dtype)

[4.   5.   9.35]
<class 'numpy.ndarray'>
float64


In [151]:
c = np.array(['A', 2])

In [152]:
print(c)
print(type(c))
print(c.dtype)

['A' '2']
<class 'numpy.ndarray'>
<U1


In [153]:
d = np.array([[1,2,3], ['A', 'B', 'C'], ['A', 2]])

<ipython-input-153-4dff87d20c48>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  d = np.array([[1,2,3], ['A', 'B', 'C'], ['A', 2]])


In [154]:
d = np.array([[1,2,3], [4, 5, 6]])

In [155]:
print(d)
print(type(d))
print(d.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int32


In [197]:
e = np.array([['A', 'B', 'C'], ['D', 'E', 'F'], [1,2,3]])
#e = np.array([['A', 'B', 'C'], ['D', 'E', 'F'], [1,2,3], ['G', 4]]) #Doesn't work

In [249]:
f = np.array([[['A', 'B', 'C'], ['D', 'E', 'F']], 
              [[1, 2, 3], [4, 5, 6]], 
              [['G', 7, 8], ['H', 9, 10]], 
              [[11, 12, 13], [14, 15 ,16]]])

In [250]:
print(f)
print(type(f))
print(f.dtype)

[[['A' 'B' 'C']
  ['D' 'E' 'F']]

 [['1' '2' '3']
  ['4' '5' '6']]

 [['G' '7' '8']
  ['H' '9' '10']]

 [['11' '12' '13']
  ['14' '15' '16']]]
<class 'numpy.ndarray'>
<U2


In [187]:
print(e)
print(type(e))
print(e.dtype)

[['A' 'B' 'C']
 ['D' 'E' 'F']
 ['1' '2' '3']]
<class 'numpy.ndarray'>
<U1


In [217]:
print(a * b)
print((a * (b * d)) + a - d)

[ 4.  10.  37.4]
[[ 4.  20.  40.4]
 [13.   2.  40.4]]


In [218]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)
print(f.ndim)

1
1
1
2
2
3


In [227]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(e.shape)
print(f.shape)

(3,)
(3,)
(2,)
(2, 3)
(3, 3)
(4, 2, 3)


# Acessing/Changing  Elements 

In [161]:
# Get a specific element > index[row, column]

In [162]:
print(a)
a[1]

[1 2 3]


2

In [163]:
print(d)
print('\n', d[1, 2])
d[:, 2]
#d[1,:] == d[1]

[[1 2 3]
 [4 5 6]]

 6


array([3, 6])

In [169]:
d[:, 2] = 1
d

array([[1, 2, 1],
       [4, 5, 1]])

In [174]:
print(a[2] == 4)
a[2] = 4
print(a[2] == 4)
a

False
True


array([1, 2, 4])

In [177]:
d[1, 1] = 0

In [178]:
d

array([[1, 2, 1],
       [4, 0, 1]])

In [189]:
e

array([['A', 'B', 'C'],
       ['D', 'E', 'F'],
       ['1', '2', '3']], dtype='<U1')

In [205]:
e[:,1]

array(['B', 'E', '2'], dtype='<U1')

In [248]:
f

array([[['A', 'B', 'C'],
        ['D', 'E', 'F']],

       [['1', '2', '3'],
        ['4', '5', '6']],

       [['G', '7', '8'],
        ['H', '9', '10']],

       [['11', '12', '13'],
        ['14', '15', '16']]], dtype='<U2')

In [268]:
f[0,0,0]

'A'

In [269]:
f[3, :, 2]

array(['13', '16'], dtype='<U2')

In [270]:
f[:,:,2]

array([['C', 'F'],
       ['3', '6'],
       ['8', '10'],
       ['13', '16']], dtype='<U2')

In [288]:
f[:, :, 1] = 6 + 90
print(f)

[[['A' '96' 'A']
  ['D' '96' 'D']]

 [['1' '96' '1']
  ['4' '96' '4']]

 [['G' '96' 'G']
  ['H' '96' 'H']]

 [['11' '96' '11']
  ['14' '96' '14']]]


In [287]:
f[:,:, 1+1] = f[:,:,0]
print(f)

[[['A' 'ND' 'A']
  ['D' 'ND' 'D']]

 [['1' 'ND' '1']
  ['4' 'ND' '4']]

 [['G' 'ND' 'G']
  ['H' 'ND' 'H']]

 [['11' 'ND' '11']
  ['14' 'ND' '14']]]


In [427]:
f[3,1,1] = f[0, 0, 0] + f[1, 1, 0]

In [428]:
f

array([[['2', '96', '1'],
        ['2', '96', '1']],

       [['1', '96', '1'],
        ['4', '96', '1']],

       [['5', '96', '1'],
        ['5', '96', '1']],

       [['11', '96', '1'],
        ['14', '24', '1']]], dtype='<U2')

In [429]:
f[3,1,1]

'24'

In [426]:
f[0,0,0]

'2'

In [423]:
f[1, 1, 0]

'4'

# Different Types of Arrays

In [431]:
# 0s Matrix

In [432]:
#23:15