In [3]:
import numpy as np

# Types of Array's

In [147]:
a = np.array([1,2,3])

In [148]:
print(a)
print(type(a))
print(a.dtype)

[1 2 3]
<class 'numpy.ndarray'>
int32


In [149]:
b = np.array([4.0, 5, 9.35])

In [150]:
print(b)
print(type(b))
print(b.dtype)

[4.   5.   9.35]
<class 'numpy.ndarray'>
float64


In [151]:
c = np.array(['A', 2])

In [152]:
print(c)
print(type(c))
print(c.dtype)

['A' '2']
<class 'numpy.ndarray'>
<U1


In [153]:
d = np.array([[1,2,3], ['A', 'B', 'C'], ['A', 2]])

<ipython-input-153-4dff87d20c48>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  d = np.array([[1,2,3], ['A', 'B', 'C'], ['A', 2]])


In [154]:
d = np.array([[1,2,3], [4, 5, 6]])

In [155]:
print(d)
print(type(d))
print(d.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int32


In [197]:
e = np.array([['A', 'B', 'C'], ['D', 'E', 'F'], [1,2,3]])
#e = np.array([['A', 'B', 'C'], ['D', 'E', 'F'], [1,2,3], ['G', 4]]) #Doesn't work

In [249]:
f = np.array([[['A', 'B', 'C'], ['D', 'E', 'F']], 
              [[1, 2, 3], [4, 5, 6]], 
              [['G', 7, 8], ['H', 9, 10]], 
              [[11, 12, 13], [14, 15 ,16]]])

In [250]:
print(f)
print(type(f))
print(f.dtype)

[[['A' 'B' 'C']
  ['D' 'E' 'F']]

 [['1' '2' '3']
  ['4' '5' '6']]

 [['G' '7' '8']
  ['H' '9' '10']]

 [['11' '12' '13']
  ['14' '15' '16']]]
<class 'numpy.ndarray'>
<U2


In [187]:
print(e)
print(type(e))
print(e.dtype)

[['A' 'B' 'C']
 ['D' 'E' 'F']
 ['1' '2' '3']]
<class 'numpy.ndarray'>
<U1


In [217]:
print(a * b)
print((a * (b * d)) + a - d)

[ 4.  10.  37.4]
[[ 4.  20.  40.4]
 [13.   2.  40.4]]


In [218]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)
print(f.ndim)

1
1
1
2
2
3


In [227]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(e.shape)
print(f.shape)

(3,)
(3,)
(2,)
(2, 3)
(3, 3)
(4, 2, 3)


# Acessing/Changing  Elements 

In [161]:
# Get a specific element > index[row, column]

In [162]:
print(a)
a[1]

[1 2 3]


2

In [163]:
print(d)
print('\n', d[1, 2])
d[:, 2]
#d[1,:] == d[1]

[[1 2 3]
 [4 5 6]]

 6


array([3, 6])

In [169]:
d[:, 2] = 1
d

array([[1, 2, 1],
       [4, 5, 1]])

In [174]:
print(a[2] == 4)
a[2] = 4
print(a[2] == 4)
a

False
True


array([1, 2, 4])

In [177]:
d[1, 1] = 0

In [178]:
d

array([[1, 2, 1],
       [4, 0, 1]])

In [189]:
e

array([['A', 'B', 'C'],
       ['D', 'E', 'F'],
       ['1', '2', '3']], dtype='<U1')

In [205]:
e[:,1]

array(['B', 'E', '2'], dtype='<U1')

In [248]:
f

array([[['A', 'B', 'C'],
        ['D', 'E', 'F']],

       [['1', '2', '3'],
        ['4', '5', '6']],

       [['G', '7', '8'],
        ['H', '9', '10']],

       [['11', '12', '13'],
        ['14', '15', '16']]], dtype='<U2')

In [268]:
f[0,0,0]

'A'

In [269]:
f[3, :, 2]

array(['13', '16'], dtype='<U2')

In [270]:
f[:,:,2]

array([['C', 'F'],
       ['3', '6'],
       ['8', '10'],
       ['13', '16']], dtype='<U2')

In [288]:
f[:, :, 1] = 6 + 90
print(f)

[[['A' '96' 'A']
  ['D' '96' 'D']]

 [['1' '96' '1']
  ['4' '96' '4']]

 [['G' '96' 'G']
  ['H' '96' 'H']]

 [['11' '96' '11']
  ['14' '96' '14']]]


In [287]:
f[:,:, 1+1] = f[:,:,0]
print(f)

[[['A' 'ND' 'A']
  ['D' 'ND' 'D']]

 [['1' 'ND' '1']
  ['4' 'ND' '4']]

 [['G' 'ND' 'G']
  ['H' 'ND' 'H']]

 [['11' 'ND' '11']
  ['14' 'ND' '14']]]


In [427]:
f[3,1,1] = f[0, 0, 0] + f[1, 1, 0]

In [428]:
f

array([[['2', '96', '1'],
        ['2', '96', '1']],

       [['1', '96', '1'],
        ['4', '96', '1']],

       [['5', '96', '1'],
        ['5', '96', '1']],

       [['11', '96', '1'],
        ['14', '24', '1']]], dtype='<U2')

In [429]:
f[3,1,1]

'24'

In [426]:
f[0,0,0]

'2'

In [423]:
f[1, 1, 0]

'4'

# Other method's for Arrays

In [1]:
import numpy as np

In [2]:
print(np.zeros(5)) # 0s Matrix
print('\n', np.zeros((2,3)))

[0. 0. 0. 0. 0.]

 [[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
np.zeros((2,3,4), dtype = 'int8')

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int8)

In [5]:
np.ones((2,3,4), dtype = 'int8') # 1s Matrix

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

In [6]:
# Any other number

In [2]:
g = np.array([[[1, 2, 3], [4, 5, 6]], 
              [[1, 2, 3], [4, 5, 6]], 
              [[1, 2, 3], [4, 5, 6]], 
              [[1, 2, 3], [4, 5, 6]]])

In [3]:
np.full((2,2), 11, dtype = 'int8')

array([[11, 11],
       [11, 11]], dtype=int8)

In [4]:
np.full(g.shape, 2)

array([[[2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2]]])

In [6]:
np.full_like(g, 2) #Full_lyke

array([[[2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2]]])

In [27]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
arr = np.array([[1,2,3]])

np.repeat(arr, 3, axis = 0)

In [46]:
np.repeat(arr, 3) #Axis = 1 for default

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

# Random methods

In [11]:
np.random.rand(4,2) #(row, columns) # Random Decimal numbers

array([[0.06365771, 0.29027441],
       [0.82507451, 0.74902553],
       [0.13536109, 0.26806603],
       [0.32804016, 0.6666871 ]])

In [22]:
np.random.randint(75, 90) #Where it start/end # Random Integer numbers ## low >= high

89

In [25]:
np.random.randint(25, size = (4,2)) #(row, columns) 

array([[ 4, 22],
       [14, 22],
       [12, 10],
       [ 0, 10]])

# Copying Arrays 

In [56]:
h = np.array([1,2,3,4])
i = h

In [57]:
print(h)
print(i)

[1 2 3 4]
[1 2 3 4]


In [58]:
i[0] = 3

In [59]:
print(h)
print(i)

[3 2 3 4]
[3 2 3 4]


In [61]:
i = h.copy() # .copy() to make real copys

In [62]:
print(h)
print(i)

[3 2 3 4]
[3 2 3 4]


In [63]:
i[0] = 7

In [64]:
print(h)
print(i)

[3 2 3 4]
[7 2 3 4]


# Statics

In [11]:
stat = np.array([[1,2,3,4], [5,6,7,8]])

In [12]:
print(np.min(stat))
np.min(stat, axis = 1)

1


array([1, 5])

In [13]:
print(np.max(stat))
np.max(stat, axis = 1)

8


array([4, 8])

In [18]:
np.sum(stat)

36

# Data from external files

In [3]:
import numpy as np

In [18]:
np.genfromtxt('G:\Meu Drive\My Laboratory\Jupyter Lab\databases\datasets\data_numpy\\data01.txt', 
              delimiter = ',')

array([[ 1., 10., 20., 30., 90.],
       [ 5.,  6.,  8.,  9., 10.],
       [11., 15., 17.,  0.,  9.]])

In [21]:
j = np.genfromtxt('G:\Meu Drive\My Laboratory\Jupyter Lab\databases\datasets\data_numpy\\data02.txt', 
              delimiter = ',', dtype = int)

In [22]:
j

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 16],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [34]:
j[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [78]:
j[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [87]:
j[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])